services:
  fotoboek-video:
    image: ghcr.io/gjagils/fotoboek-video:latest
    container_name: fotoboek-video
    restart: unless-stopped
    environment:
      - BASE_URL=https://albumvideo.gerdjan.nl
      - PORT=3000
    ports:
      # Alleen nodig als je 'm niet via Cloudflare Tunnel maar rechtstreeks test
      - "3000:3000"
    volumes:
      - /volume1/homes/gjagils/fotoboek-video/videos:/app/videos
      - /volume1/homes/gjagils/fotoboek-video/data:/app/data
